package views;

import controllers.AsetController;
import controllers.PemasukanController;
import controllers.TransaksiController;
import helpers.AsetHelper;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import models.Aset;

public class TransaksiView extends javax.swing.JFrame {
    public static int selectedTransaksiId = 0;
    public static int selectedAsetId = 0;

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public JComboBox<String> getjComboBoxSource() {
        return jComboBoxSource;
    }

    public JTextArea getjTextAreaDescriptionPengeluaran() {
        return jTextAreaDescriptionPengeluaran;
    }

    public JTextField getjTextFieldAmountPengeluaran() {
        return jTextFieldAmountPengeluaran;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }
    
    public JComboBox<String> getjComboBoxTypePemasukan() {
        return jComboBoxTypePemasukan;
    }

    public void setjComboBoxTypePemasukan(JComboBox<String> jComboBoxTypePemasukan) {
        this.jComboBoxTypePemasukan = jComboBoxTypePemasukan;
    }

    public JTextArea getjTextAreaDescriptionPemasukan() {
        return jTextAreaDescriptionPemasukan;
    }

    public void setjTextAreaDescriptionPemasukan(JTextArea jTextAreaDescriptionPemasukan) {
        this.jTextAreaDescriptionPemasukan = jTextAreaDescriptionPemasukan;
    }

    public JTextField getjTextFieldAmountPemasukan() {
        return jTextFieldAmountPemasukan;
    }

    public void setjTextFieldAmountPemasukan(JTextField jTextFieldAmountPemasukan) {
        this.jTextFieldAmountPemasukan = jTextFieldAmountPemasukan;
    }

    public JTextField getjTextFieldSourcePemasukan() {
        return jTextFieldSourcePemasukan;
    }

    public void setjTextFieldSourcePemasukan(JTextField jTextFieldSourcePemasukan) {
        this.jTextFieldSourcePemasukan = jTextFieldSourcePemasukan;
    }

//    TransaksiController c;
    public TransaksiView() {
        initComponents();
        
        AsetHelper helper = new AsetHelper();
        List<Aset> data = helper.getAllData();

        Set<String> sourceSet = new HashSet<>();
        for (Aset aset : data) {
            sourceSet.add(aset.getSource());
        }

        jComboBoxSource.setModel(new javax.swing.DefaultComboBoxModel<>(
                sourceSet.toArray(new String[0])
        ));
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelTransaksi = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxSource = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAmountPengeluaran = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescriptionPengeluaran = new javax.swing.JTextArea();
        jButtonSubmitPengeluaran = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxTypePemasukan = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldSourcePemasukan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDescriptionPemasukan = new javax.swing.JTextArea();
        jButtonSubmitPemasukan = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldAmountPemasukan = new javax.swing.JTextField();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(232, 245, 233));

        jLabelTransaksi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTransaksi.setText("Transaksi");

        jPanel1.setBackground(new java.awt.Color(232, 245, 233));

        jLabel6.setText("Transaction Source");

        jComboBoxSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxSource.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxSourceItemStateChanged(evt);
            }
        });
        jComboBoxSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSourceActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount (Rp)");

        jLabel5.setText("Description");

        jTextAreaDescriptionPengeluaran.setColumns(20);
        jTextAreaDescriptionPengeluaran.setRows(5);
        jScrollPane2.setViewportView(jTextAreaDescriptionPengeluaran);

        jButtonSubmitPengeluaran.setText("Submit");
        jButtonSubmitPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitPengeluaranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxSource, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldAmountPengeluaran, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSubmitPengeluaran))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldAmountPengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmitPengeluaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pengeluaran", jPanel1);

        jPanel3.setBackground(new java.awt.Color(232, 245, 233));

        jLabel10.setText("Type");

        jComboBoxTypePemasukan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai", "Debit", "Lainnya" }));
        jComboBoxTypePemasukan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTypePemasukanItemStateChanged(evt);
            }
        });
        jComboBoxTypePemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTypePemasukanActionPerformed(evt);
            }
        });

        jLabel11.setText("Source");

        jTextFieldSourcePemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSourcePemasukanActionPerformed(evt);
            }
        });

        jLabel12.setText("Description");

        jTextAreaDescriptionPemasukan.setColumns(20);
        jTextAreaDescriptionPemasukan.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDescriptionPemasukan);

        jButtonSubmitPemasukan.setText("Submit");
        jButtonSubmitPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitPemasukanActionPerformed(evt);
            }
        });

        jLabel13.setText("Amount (Rp)");

        jTextFieldAmountPemasukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAmountPemasukanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jComboBoxTypePemasukan, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSourcePemasukan, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAmountPemasukan, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jButtonSubmitPemasukan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBoxTypePemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldSourcePemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldAmountPemasukan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmitPemasukan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pemasukan", jPanel3);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTransaksi)
                .addGap(171, 171, 171))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelTransaksi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBack)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitPengeluaranActionPerformed
        String source = (String) jComboBoxSource.getSelectedItem();
        
        int amount = 0;
        try {
        amount = Integer.parseInt(jTextFieldAmountPengeluaran.getText());
        } catch (NumberFormatException e) {
        }
        
        if (source == null) {
            JOptionPane.showMessageDialog(this, "Sumber aset belum tersedia","Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String description = jTextAreaDescriptionPengeluaran.getText();
        Dashboard dashboard = new Dashboard(); // buat sekali

        TransaksiController transaksi = new TransaksiController(dashboard);
        
        if(TransaksiView.selectedTransaksiId != 0) {
            transaksi.updateTransaksi("Pengeluaran", amount, description, source);
        } else {
            transaksi.tambahTransaksi("Pengeluaran", amount, description, source);
        }
        
        
        dispose();
        
    }//GEN-LAST:event_jButtonSubmitPengeluaranActionPerformed

    private void jComboBoxSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSourceActionPerformed

    private void jComboBoxSourceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxSourceItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSourceItemStateChanged

    private void jComboBoxTypePemasukanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTypePemasukanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypePemasukanItemStateChanged

    private void jComboBoxTypePemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTypePemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTypePemasukanActionPerformed

    private void jButtonSubmitPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitPemasukanActionPerformed
        // TODO add your handling code here:
        PemasukanController pemasukan = new PemasukanController(this);
        
        if(TransaksiView.selectedAsetId != 0) {
            pemasukan.updatePemasukan();
        } else {
            pemasukan.addNewPemasukan();
        }
        dispose();
    }//GEN-LAST:event_jButtonSubmitPemasukanActionPerformed

    private void jTextFieldSourcePemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSourcePemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSourcePemasukanActionPerformed

    private void jTextFieldAmountPemasukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAmountPemasukanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAmountPemasukanActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        dispose();
        Dashboard d = new Dashboard();
        d.setVisible(true);
        d.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonBackActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TransaksiView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSubmitPemasukan;
    private javax.swing.JButton jButtonSubmitPengeluaran;
    private javax.swing.JComboBox<String> jComboBoxSource;
    private javax.swing.JComboBox<String> jComboBoxTypePemasukan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaDescriptionPemasukan;
    private javax.swing.JTextArea jTextAreaDescriptionPengeluaran;
    private javax.swing.JTextField jTextFieldAmountPemasukan;
    private javax.swing.JTextField jTextFieldAmountPengeluaran;
    private javax.swing.JTextField jTextFieldSourcePemasukan;
    // End of variables declaration//GEN-END:variables

}
